(******************************************************************************)
(*                                                                            *)
(*                  Gold Panning: Density Stratification Logic                *)
(*                                                                            *)
(*     Formalizes placer gold recovery: density differential (Au 19.3 g/cm³   *)
(*     vs SiO₂ 2.65 g/cm³), particle stratification under agitation,          *)
(*     classification (flour/fine/flake/picker/nugget by mesh). Proves        *)
(*     heavier particles sink monotonically; recovery efficiency bounds.      *)
(*     Depends on settling-verified.                                          *)
(*                                                                            *)
(*     "Gold is where you find it."                                           *)
(*     - Prospector's proverb                                                 *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 7, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
